### ISSUE TITLE
Creating Shift is not working

### ISSUE THREAD

**Issue by NatiG100** [Resgrid/Core#112]
- I was trying to create a new shift, but I couldn't insert start time and end time in the input fields
- Even if i tried to bypass that by copying and pasting, creating a new shift won't work
![image](https://github.com/Resgrid/Core/assets/87175869/93976028-69e1-4478-864f-4c43c972874d)

**Comment by ucswift** [comment]
@NatiG100 thanks for reporting, I'll take a look.

**Comment by NatiG100** [comment]
@ucswift Thank you for taking the time to look into this. I appreciate it.

**Comment by ucswift** [comment]
Hey @NatiG100, yeah, I confirmed the issue and found some more. The underlying problem is the JS file for the picker control is either not loading correctly or not found. I'm working a fix for that now, plus I noticed some URL's are still pointing to the hosted version (like the default profile image) that is causing problems. I should have a fix and a new release out here soon.

**Comment by ucswift** [comment]
Found and fixed the issue with https://github.com/Resgrid/Core/commit/a57583ea0b65d6be0bef8fa282879119299243a6 going to do some testing and validation before I push out new docker images.

**Comment by NatiG100** [comment]
@ucswift Appreciate your quick response on this one. Looking forward to the new docker images
